version: '3'

services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/user/src/app
    ports:
      - 8000:3000
    depends_on:
      - backend


  backend:
    build: ./backend
    volumes:
      - ./backend:/user/src/app
    ports:
      - 5000:5000

    restart: always